### ISSUE TITLE
closure example?

### ISSUE THREAD

**Issue by kzc** [FastVM/minivm#13]
Thanks for sharing this very interesting project. 

For the most part the code is quite easy to follow, but I'm having difficulty recreating this construct described in the readme:

> to emulate closures arrays can be called as functions if the first item in that array is a function.

I've been unable to make an example of a closure in paka script using this technique.  It is not clear how to have a reference to a paka function in order to put it into an array since using the function name will call the function in question.  Also, as far as I can tell, paka variables cannot be assigned function `def`s.  Might you post the paka equivalent of the following javascript?

```
$ cat closure.js 
function closure(a) {
    return function(b) {
        return a + b;
    };
}
var f = closure(2);
console.log(f(3));
console.log(f(7));
```
``` 
$ node closure.js 
5
9
```

**Comment by kzc** [comment]
I was unable to make closures work with paka using arrays with a function as the first element. Perhaps closures might be possible with raw minvm byte code. I didn't pursue it further.

**Comment by ShawSumma** [comment]
Closures in that manner are TODO.
I need to rethink how MiniVM handles arrays first.
