### ISSUE TITLE
supported platforms

### ISSUE THREAD

**Issue by mgood7123** [FastVM/minivm#21]
What cpu platforms are supported?

Eg x86, arm, mips, powerpc, ect

**Comment by ShawSumma** [comment]
I test on windows x86_64, macos arm, linux x86_64 and freebsd x86_64
It should run on about anything it can compile on.

**Comment by ShawSumma** [comment]
It should now support anything with a c compiler through `--target=tb-cc`. That compiles MiniVM IR to C with TB.

I've also got the web/ folder that is a web version fully jitting with WASM.

MiniVM now uses TB so if you want to add a new targe to MiniVM talk to @RealNeGate
