### ISSUE TITLE
Using minivm on Windows is no use

### ISSUE THREAD

**Issue by none-None1** [FastVM/minivm#28]
I tried `.\minivm --dump-time -e 'print("hello")'` in powershell, it doesn't print anything.

**Comment by ShawSumma** [comment]
It's broken, sorry. I'll work on a 0.0.2

**Comment by ShawSumma** [comment]
@none-None1 if you would try again with v0.0.2 that would be great. I don't know your exact setup but i think it should work.

**Comment by none-None1** [comment]
I used 0.0.3 and it works only in the prompt but not files

For example
```shell
> ./minivm
lua> print('hello')
hello
```
Works correctly, but:
```shell
> ./minivm --dump-time fib.lua
error: type error: only functions can be called
took: 6.000ms
```
doesn't.

**Comment by ShawSumma** [comment]
can you post the source code of fib.lua, something other than quotes is def broken.

**Comment by ShawSumma** [comment]
I can't seem to reproduce this error.

**Comment by none-None1** [comment]
Thanks
